
# This workflow is designed to build and deploy your Next.js app to Firebase App Hosting.
#
# 1. SETUP WORKLOAD IDENTITY FEDERATION:
#    - Go to your Google Cloud project.
#    - Enable the "Identity and Access Management (IAM) API".
#    - Create a new "Workload Identity Pool" (e.g., "github-pool").
#    - Create a "Provider" within that pool for GitHub. Set the Issuer URL to "https://token.actions.githubusercontent.com".
#    - Create a "Service Account" (e.g., "github-actions-deployer").
#    - Grant the "Firebase App Hosting Admin" role to this service account.
#    - On the service account's permissions page, grant it the "Workload Identity User" role, specifying your new workload identity pool.
#
# 2. ADD GITHUB SECRETS:
#    - In your GitHub repository, go to "Settings" > "Secrets and variables" > "Actions".
#    - Create a secret named `GCP_PROJECT_ID` with your Google Cloud Project ID.
#    - Create a secret named `GCP_SERVICE_ACCOUNT` with the full email of the service account you created (e.g., "github-actions-deployer@<your-project-id>.iam.gserviceaccount.com").
#    - Create a secret named `GCP_WORKLOAD_IDENTITY_PROVIDER` with the full resource name of your provider (e.g., projects/<number>/locations/global/workloadIdentityPools/<pool-id>/providers/<provider-id>).
#
# 3. CONFIGURE THE FILE BELOW:
#    - Replace `<YOUR_BACKEND_ID>` with your Firebase App Hosting backend ID.
#    - Replace `<YOUR_BACKEND_LOCATION>` with the region your backend is in (e.g., us-central1).

name: Deploy to Firebase App Hosting

on:
  push:
    branches: ["master"] # This will trigger the deployment on every push to the master branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write" # Required for authentication with Google Cloud

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a version compatible with your project
          cache: "npm"

      - name: Install dependencies
        run: npm ci # 'ci' is faster and more reliable for CI/CD environments

      - name: Build the Next.js app
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      - name: Deploy to Firebase App Hosting
        uses: "google-github-actions/deploy-apphosting@v0"
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
          backend_id: "<YOUR_BACKEND_ID>" # <-- IMPORTANT: Replace with your backend ID
          location: "<YOUR_BACKEND_LOCATION>" # <-- IMPORTANT: Replace with your backend location (e.g., us-central1)
